default_platform(:ios)

platform :ios do
  desc 'Upload an existing IPA to TestFlight'
  lane :upload_testflight do
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch('APP_STORE_CONNECT_KEY_ID'),
      issuer_id: ENV.fetch('APP_STORE_CONNECT_ISSUER_ID'),
      key_filepath: ENV.fetch('APP_STORE_CONNECT_API_KEY_PATH'),
      duration: 1200,
      in_house: false
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: ENV.fetch('IPA_PATH'),
      app_identifier: ENV.fetch('APP_IDENTIFIER'),
      skip_waiting_for_build_processing: true
    )
  end
end
